version: '3.8'
services:
  # Base de Datos
  db:
    image: postgres:15-alpine
    restart: always
    container_name: repo_datascience-db-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: paty
      POSTGRES_DB: churn_insight_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Servicio Python (IA)
  churn-service:
    build: ./churn-service
    restart: always
    container_name: repo_datascience-churn-service-1
    ports:
      - "8000:8000"

  # Backend Java
  java-app:
    build: ./app
    restart: always
    container_name: repo_datascience-java-app-1
    ports:
      - "8080:8080"
    environment:
      
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/churn_insight_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: paty
      
      CHURN_PREDICT_HOST: churn-service
      CHURN_PREDICT_PORT: 8000
    depends_on:
      - db
      - churn-service

  # Frontend React
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: "http://34.122.111.255:8080"
    restart: always
    container_name: repo_datascience-frontend-1
    ports:
      - "80:80"
    depends_on:
      - java-app

volumes:
  postgres_data: